[NoInterfaceObject]
interface URLUtils {
	attribute DOMString protocol;
	attribute DOMString host;
	attribute DOMString hostname;
	attribute DOMString port;
	attribute DOMString pathname;
	attribute DOMString search;
	attribute DOMString hash;
};
